Repository milvus-io/community, pull requests merged in 2022-02, with the labels that each got.

#90 Update 2020-02-26-select-index-parameters-ivf-index.md
  blog/en/2020-02-26-select-index-parameters-ivf-index.md
Labels: size/XS

#93 Add Delete
  blog/en/2022-02-07-how-milvus-deletes-streaming-data-in-distributed-cluster.md
Labels: size/L

#94 Fix code sample
  blog/en/2022-02-07-how-milvus-deletes-streaming-data-in-distributed-cluster.md
Labels: size/XS

#99 Minor fix to bitset blog
  blog/en/2022-2-14-bitset.md
Labels: size/S

#105 Create 2022-2-21-compact.md
  blog/en/2022-2-21-compact.md
Labels: size/L

#107 Update cover image in compact
  blog/en/2022-2-21-compact.md
Labels: size/XS

#108 Create 2022-02-28-how-milvus-balances-query-load-across-nodes.md
  blog/en/2022-02-28-how-milvus-balances-query-load-across-nodes.md
Labels: size/L
