Repository milvus-io/community, pull requests merged in 2022-08, with the labels that each got.

#190 Update the recommended reads for deep dive blogs.
  blog/en/deep-dive-1-milvus-architecture-overview.md
  blog/en/deep-dive-2-milvus-sdk-and-api.md
  blog/en/deep-dive-3-data-processing.md
  blog/en/deep-dive-4-data-insertion-and-data-persistence.md
  blog/en/deep-dive-5-real-time-query.md
  blog/en/deep-dive-6-oss-qa.md
  blog/en/deep-dive-7-query-expression.md
  blog/en/deep-dive-8-knowhere.md
Labels: size/M

#191 Update the recommended reads for new 2.0 feature blogs
  blog/en/2022-02-07-how-milvus-deletes-streaming-data-in-distributed-cluster.md
  blog/en/2022-02-28-how-milvus-balances-query-load-across-nodes.md
  blog/en/2022-1-27-milvus-2-0-a-glimpse-at-new-features.md
  blog/en/2022-2-14-bitset.md
  blog/en/2022-2-21-compact.md
Labels: size/M

#193 Fix id in whats-new-in-milvus-2-1.md
  blog/en/2022-08-05-whats-new-in-milvus-2-1.md
Labels: size/XS

#194 String feature blog
  blog/en/2022-08-08-How-to-use-string-data-to-empower-your-similarity-search-applications.md
Labels: size/L

#196 updated string blog
  blog/en/2022-08-08-How-to-use-string-data-to-empower-your-similarity-search-applications.md
Labels: size/XS

#197 Create embedded-milvus.md
  blog/en/embedded-milvus.md
Labels: size/L

#199 Benchmark blog
  blog/en/2022-08-16-Benchmark-Quick-Setup.md
Labels: size/M

#209 Update 2022-08-16-Benchmark-Quick-Setup.md
  blog/en/2022-08-16-Benchmark-Quick-Setup.md
Labels: size/S
