Repository milvus-io/community, pull requests merged in 2022-01, with the labels that each got.

#61 cover image update and remove the fastapi vs flask blog
  blog/en/2021-11-08-frustrated-with-new-data-our-vector-database-can-help.md
  blog/en/2021-11-19-run-milvus-2.0-on-windows.md
  blog/en/2021-11-26-accelerating-candidate-generation-in-recommender-systems-using-milvus-paired-with-paddlepaddle.md
  blog/en/2021-12-03-why-to-choose-fastapi-over-flask.md
  blog/en/2021-12-21-milvus-2.0.md
  blog/en/2021-12-31-get-started-with-milvus-cli.md
  blog/en/2022-01-07-year-in review.md
Labels: size/S

#67 add recommend blog
  blog/en/2021-12-31-get-started-with-milvus-cli.md
Labels: size/XS

#68 Update 2021-12-21-milvus-2.0.md
  blog/en/2021-12-21-milvus-2.0.md
Labels: size/XS

#72 Update image caption format in SmartNews blog
  blog/en/2022-01-20-story-of-smartnews.md
Labels: size/XS

#74 Added 2021-01-25 new blog
  blog/en/2022-1-25-annoucing-general-availability-of-milvus-2-0.md
Labels: size/M

#75 Update 2022-01-20-story-of-smartnews.md
  blog/en/2022-01-20-story-of-smartnews.md
Labels: size/XS

#76 Unrecommend Year in Review
  blog/en/2022-01-07-year-in-review.md
Labels: size/XS

#80 Added the opening address to 2.0GA blog
  blog/en/2022-1-25-annoucing-general-availability-of-milvus-2-0.md
Labels: size/S

#81 Update 2022-01-20-story-of-smartnews.md
  blog/en/2022-01-20-story-of-smartnews.md
Labels: size/XS

#82 Add Medium API
  .DS_Store
  .github/workflows/update_medium.yml
  .gitignore
  blog/.DS_Store
  blog/en/.DS_Store
  package.json
  postMedium.md
  yarn.lock
Labels: size/L

#87 Add new blog - new feature
  blog/en/2022-1-27-milvus-2-0-a-glimpse-at-new-features.md
Labels: size/L

#88 New feature fix
  blog/en/2022-1-27-milvus-2-0-a-glimpse-at-new-features.md
Labels: size/M
