Repository milvus-io/community, pull requests merged in 2022-03, with the labels that each got.

#64 Update community_roles
  community_roles
Labels: size/XS

#104 Add mentorship guidelines
  community-mentorship.md
Labels: size/M

#118 Add Attu
  blog/en/2022-03-10-manage-your-milvus-vector-database-with-one-click-simplicity.md
Labels: size/L

#122 Create deep-dive-1-milvus-architecture-overview.md
  blog/en/deep-dive-1-milvus-architecture-overview.md
Labels: size/L

#124 Update deep-dive-1-milvus-architecture-overview.md
  blog/en/deep-dive-1-milvus-architecture-overview.md
Labels: size/XS

#125 Update deep-dive-1-milvus-architecture-overview.md
  blog/en/deep-dive-1-milvus-architecture-overview.md
Labels: size/XS

#131 Update cover images.
  blog/en/2021-09-28-hactoberfeat-warmup.md
  blog/en/2021-10-10-milvus-helps-analys-vedios.md
  blog/en/2021-10-22-apply-configuration-changes-on-milvus-2.md
  blog/en/2021-11-07-how-to-modify-milvus-advanced-configurations.md
  blog/en/2021-11-08-frustrated-with-new-data-our-vector-database-can-help.md
  blog/en/2021-11-10-milvus-hacktoberfest-2021.md
  blog/en/2021-11-19-run-milvus-2.0-on-windows.md
  blog/en/2021-11-26-accelerating-candidate-generation-in-recommender-systems-using-milvus-paired-with-paddlepaddle.md
  blog/en/2021-12-10-image-based-trademark-similarity-search-system-a-smarter-solution-to-ip-protection.md
  blog/en/2021-12-21-milvus-2.0.md
  blog/en/2021-12-31-get-started-with-milvus-cli.md
  blog/en/2022-01-07-year-in-review.md
  blog/en/2022-01-20-story-of-smartnews.md
  blog/en/2022-02-07-how-milvus-deletes-streaming-data-in-distributed-cluster.md
  blog/en/2022-02-28-how-milvus-balances-query-load-across-nodes.md
  blog/en/2022-03-10-manage-your-milvus-vector-database-with-one-click-simplicity.md
  blog/en/2022-1-25-annoucing-general-availability-of-milvus-2-0.md
Labels: size/M

#132 Create deep-dive-2-milvus-sdk-and-api.md
  blog/en/deep-dive-2-milvus-sdk-and-api.md
Labels: size/M

#135 Update deep-dive-1-milvus-architecture-overview.md
  blog/en/deep-dive-1-milvus-architecture-overview.md
  blog/en/deep-dive-2-milvus-sdk-and-api.md
Labels: size/M

#134 Create deep-dive-3-data-processing.md
  blog/en/deep-dive-3-data-processing.md
Labels: size/L

#136 Remove Manual Load Balance
  blog/en/2022-02-28-how-milvus-balances-query-load-across-nodes.md
Labels: size/M
