Repository milvus-io/community, pull requests merged in 2023-11, with the labels that each got.

#274 release a new blog- comparing vector darabases
  blog/en/comparing-vector-database-vector-search-plugin-vector-search-libraries.md
Labels: size/L

#275 milvus-introduced-mmap-for-redefined-data-management-increased-storag…
  blog/en/milvus-introduced-mmap-for-redefined-data-management-increased-storage-capability.md
Labels: size/M

#276 update the title to the blog - milvus-introduced-mmap
  blog/en/milvus-introduced-mmap-for-redefined-data-management-increased-storage-capability.md
Labels: size/XS

#277 Update the cover image - milvus-introduced-mmap
  blog/en/milvus-introduced-mmap-for-redefined-data-management-increased-storage-capability.md
Labels: size/XS

#278 fix an image
  blog/en/milvus-introduced-mmap-for-redefined-data-management-increased-storage-capability.md
Labels: size/XS

#279 update blog cover - why and when you need a database
  blog/en/why-and-when-you-need-a-purpose-built-vector-database.md
Labels: size/XS

#280 Update blog cover - comparing vector database
  blog/en/comparing-vector-database-vector-search-plugin-vector-search-libraries.md
Labels: size/XS

#281 release a new blog - revealing-milvus-2-3-2-and-milvus-2-3-3
  blog/en/revealing-milvus-2-3-2-and-milvus-2-3-3.md
Labels: size/M

#282 fix a bug - release blog
  blog/en/revealing-milvus-2-3-2-and-milvus-2-3-3.md
Labels: size/XS

#283 release a blog - milvus-embraces-nats-messaging
  blog/en/milvus-embraces-nats-messaging.md
Labels: size/L
