Repository milvus-io/community, pull requests merged in 2024-01, with the labels that each got.

#291 Release a blog: Milvus in 2023
  blog/en/milvus-in-2023-unprecedented-vector-database-amidst-tech-buzz.md
Labels: size/L

#292 update blog cover
  blog/en/milvus-in-2023-unprecedented-vector-database-amidst-tech-buzz.md
Labels: size/XS

#293 add home page banner info file
  homepage/README.md
  homepage/index.json
Labels: size/S

#294 update meta title
  blog/en/milvus-2210-and-2211-enhanced-stability-and-better-user-experience.md
Labels: size/XS

#295 fix metat title
  blog/en/milvus-2210-and-2211-enhanced-stability-and-better-user-experience.md
Labels: size/XS

#296 Delete milvus-in-2023-unprecedented-vector-database-amidst-tech-buzz.md
  blog/en/milvus-in-2023-unprecedented-vector-database-amidst-tech-buzz.md
Labels: size/L

#297 Update index.json
  homepage/index.json
Labels: size/XS

#298 publish a post - Milvus 2.3.4
  blog/en/milvus-2–3-4-faster-searches-expanded-data support-improved-monitoring-and-more.md
  homepage/index.json
Labels: size/M

#299 add a subtitle to Milvus 2.3.4 release blog
  blog/en/milvus-2-2-12-easier-access-faster-vector-search-speeds-better-user-experience.md
  blog/en/milvus-2–3-4-faster-searches-expanded-data support-improved-monitoring-and-more.md
Labels: size/XS

#300 fix a url
  blog/en/milvus-2–3-4-faster-searches-expanded-data-support-improved-monitoring-and-more.md
Labels: size/XS

#301 bugfix
  blog/en/milvus-2-3-4-faster-searches-expanded-data-support-improved-monitoring-and-more.md
  homepage/index.json
Labels: size/XS

#302 Create top-10-keywords-dominates-milvus-community-in-2023.md
  blog/en/top-10-keywords-dominates-milvus-community-in-2023.md
Labels: size/L

#303 update homepage
  blog/en/top-10-keywords-dominates-milvus-community-in-2023.md
  homepage/index.json
Labels: size/M

#304 Update top-10-keywords-dominates-milvus-community-in-2023.md
  blog/en/top-10-keywords-dominates-milvus-community-in-2023.md
Labels: size/XS
