Repository milvus-io/community, pull requests merged in 2024-12, with the labels that each got.

#352 New blog: How to Contribute to Milvus
  blog/en/how-to-contribute-to-milvus-a-quick-start-for-developers.md
Labels: size/L

#353 Update the hubspot link
  blog/en/join-milvus-office-hours-to-get-support-from-vectordb-experts.md
Labels: size/XS

#354 Repost: Build Multitenancy RAG with Milvus
  blog/en/build-multi-tenancy-rag-with-milvus-best-practices-part-one.md
Labels: size/L

#355 Update the invitation link
  blog/en/join-milvus-office-hours-to-get-support-from-vectordb-experts.md
Labels: size/XS

#356 Publish new blog: Introducing Milvus 2.5
  blog/en/introduce-milvus-2-5-full-text-search-powerful-metadata-filtering-and-more.md
Labels: size/L

#357 Publish new blog: semantic search vs full-text search
  blog/en/semantic-search-vs-full-text-search-which-one-should-i-choose-with-milvus-2-5.md
Labels: size/XL

#358 Publish new blog: Getting Started with Hybrid Semantic / Full-Text Search with Milvus 2.5
  blog/en/get-started-with-hybrid-semantic-full-text-search-with-milvus-2-5.md
Labels: size/L

#359 Publish new blog: Elasticsearch is Dead, Long Live Lexical Search
  blog/en/elasticsearch-is-dead-long-live-lexical-search.md
Labels: size/L

#360 feat: send feishu message when post medium
  .github/workflows/update_medium.yml
  postMedium.md
Labels: size/L
