Repository milvus-io/community, pull requests merged in 2024-05, with the labels that each got.

#326 release new blog - optimize vector databases
  blog/en/optimize-vector-databases-enhance-rag-driven-generative-ai.md
Labels: size/L

#327 fix blog issues
  blog/en/optimize-vector-databases-enhance-rag-driven-generative-ai.md
Labels: size/M

#329 Update optimize-vector-databases-enhance-rag-driven-generative-ai.md
  blog/en/optimize-vector-databases-enhance-rag-driven-generative-ai.md
Labels: size/XS

#330 Publish Milvus Lite blog
  blog/en/introducing-milvus-lite.md
Labels: size/M
