Repository milvus-io/community, pull requests merged in 2025-08, with the labels that each got.

#454 publish deploying milvus on kubernetes just got easier with the milvu…
  blog/en/deploying-milvus-on-kubernetes-just-got-easier-with-the-milvus-operator.md
  blog/en/talk-to-vector-db-manage-milvus-via-natural-language.md
Labels: size/XL

#455 Update deploying-milvus-on-kubernetes-just-got-easier-with-the-milvus…
  blog/en/deploying-milvus-on-kubernetes-just-got-easier-with-the-milvus-operator.md
Labels: size/XS

#456 Create gpt-oss-vs-o4-mini-edge-ready-on-par-performance-dependable-no…
  blog/en/gpt-oss-vs-o4-mini-edge-ready-on-par-performance-dependable-not-mind-blowing.md
Labels: size/L

#457 Update gpt-oss-vs-o4-mini-edge-ready-on-par-performance-dependable-no…
  blog/en/gpt-oss-vs-o4-mini-edge-ready-on-par-performance-dependable-not-mind-blowing.md
Labels: size/XS

#458 Create gpt-5-review-accuracy-up-prices-down-code-strong-but-bad-for-c…
  blog/en/gpt-5-review-accuracy-up-prices-down-code-strong-but-bad-for-creativity.md
Labels: size/L

#460 Create hands-on-with-vdbbench-benchmarking-vector-databases-for-pocs-…
  blog/en/hands-on-with-vdbbench-benchmarking-vector-databases-for-pocs-that-match-production.md
Labels: size/L
