Repository milvus-io/community, pull requests merged in 2025-02, with the labels that each got.

#363 release a new blog - multimodal semantic search with image and text
  blog/en/multimodal-semantic-search-with-images-and-text.md
Labels: size/L

#364 update multimodal semantic search with images and text blog - Added links
  blog/en/multimodal-semantic-search-with-images-and-text.md
Labels: size/XS

#365 Update blog - Multimodal semantic search with images and text
  blog/en/multimodal-semantic-search-with-images-and-text.md
Labels: size/XS

#366 release-a-blog-deep-research-open-source
  blog/en/i-built-a-deep-research-with-open-source-so-can-you.md
Labels: size/L

#368 fix: fix post medium script error
  postMedium.md
Labels: size/XS

#369 update-blog-i-built-a-deep-research-with-open-source
  blog/en/i-built-a-deep-research-with-open-source-so-can-you.md
Labels: size/XS

#370 Update-multimodal-semantic-search-blog
  blog/en/i-built-a-deep-research-with-open-source-so-can-you.md
  blog/en/multimodal-semantic-search-with-images-and-text.md
Labels: size/M

#371 edit-blog-code-deep-research-article
  blog/en/i-built-a-deep-research-with-open-source-so-can-you.md
Labels: size/M

#372 update the blog image
  blog/en/i-built-a-deep-research-with-open-source-so-can-you.md
Labels: size/XS

#373 fix video issues
  blog/en/i-built-a-deep-research-with-open-source-so-can-you.md
  blog/en/multimodal-semantic-search-with-images-and-text.md
Labels: size/S

#375 blog: introduce deepsearcher
  blog/en/introduce-deepsearcher-a-local-open-source-deep-research.md
Labels: size/L

#377 publish-blog-browser-use-milvus
  blog/en/ai-for-smarter-browsing-filtering-web-content-with-pirxtral-milvus-browser-use.md
Labels: size/L

#378 update the blog
  blog/en/ai-for-smarter-browsing-filtering-web-content-with-pirxtral-milvus-browser-use.md
Labels: size/S

#379 Use MilvusClient instead of `connections`
  blog/en/how-to-get-started-with-milvus.md
Labels: size/S
